version: "3"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/project
    ports:
      - "80:80"      
      - 9222:9222
    expose:
      - "9001"
    networks:
      - symfony

networks:
  symfony:

volumes:
  # project:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: .
  mysql-db-data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /home/srodas/Docker/volumes/mysql
